name: Renovate / Renovatebot SCA Scan           # workflow name

######## IMPORTANT #########  
# Variables to set:
# type - must be set - what type of scan, [SCA, SAST, DAST, IAC]
# language - Must be set of the code must be set to know which Scanning Type / File will be used
# project_dir - Must be set to knw know which Directory to scan, " ./ " will be the default. 
# environment - Must be set to know if the pipeline should stop or continue on error - non-prod has 'continue-on-error: true' all other environments will be stopped if the scans give an error.
# non-prod has 'continue-on-error: true' all other environments will be stopped if the scans give an error-code that is not "0" !!!

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write


jobs:
  renovate-run:
    runs-on: ubuntu-latest
    environment: dvpa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repo files (debug)
        run: ls -la

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          # Optionally, specify a config file if needed:
          # RENOVATE_CONFIG_FILE: renovate.json
